# Generated by Django 6.0.5 on 2026-06-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('regular', 'Regular User'), ('premium', 'Premium User'), ('editor', 'Editor User')], default='regular', max_length=20),
        ),
    ]
