from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import WeatherForecastView, SavedQueryViewSet, ForecastManagementViewSet, FavouriteCityViewSet, \
    HistoryStatsView

router = DefaultRouter()

# Registers the ViewSet with prefix 'history'
router.register(r'history', SavedQueryViewSet, basename='history')
router.register(r'manage', ForecastManagementViewSet, basename='manage')
router.register(r'favourites', FavouriteCityViewSet, basename='favourites')

urlpatterns = [
    path('weather/', WeatherForecastView.as_view(), name='weather-forecast'),
    path('history/stats/', HistoryStatsView.as_view(), name='history-stats'),

    # Includes all the urls generated by the Router automatically
    path('', include(router.urls)),
]